<?php

namespace AppBundle\Repository;

/**
 * ChirurgieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChirurgieRepository extends \Doctrine\ORM\EntityRepository
{
}
